[project]
name = "simsort"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "networkx>=3.2.1",
    "numpy>=2.0.2",
    "scikit-learn>=1.5.2",
    "sentence-transformers>=3.2.1",
    "tensorflow>=2.18.0",
    "tensorflow-hub>=0.16.1",
]
